import { createCipheriv,createDecipheriv,createHash,randomBytes,scryptSync } from 'node:crypto';
import { copyFileSync,cpSync,existsSync,mkdirSync,readFileSync,readdirSync,rmSync,statSync,writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';
import { assertDemoDatabasePath,loadConfig,type PlatformConfig } from '../src/config.js';
import { openDatabase } from './db.js';

export interface BackupArtifact {readonly path:string;readonly sha256:string;readonly bytes:number;readonly kind:'DATABASE'|'DOCUMENT'|'METADATA'}
export interface BackupManifest {readonly version:2;readonly environment:string;readonly createdAt:string;readonly databaseFile:string;readonly sha256:string;readonly bytes:number;readonly productionBackup:false;readonly artifacts:readonly BackupArtifact[];readonly encrypted:boolean;readonly encryptionAlgorithm:'AES-256-GCM-SCRYPT'|null;readonly remoteReplication:'DISABLED_DEMO'}
export interface RemoteBackupProvider {health():{ready:boolean;provider:string};replicate(directory:string,manifest:BackupManifest):object}
export class ExternalRemoteBackupAdapter implements RemoteBackupProvider {health(){return{ready:false,provider:'external-backup-pending'};}replicate(_directory:string,_manifest:BackupManifest):never{throw new Error('EXTERNAL_BACKUP_NOT_PROVISIONED');}}

const MAGIC=Buffer.from('CELULARS-BACKUP-V1\n','utf8');
function sha256(file:string):string{return createHash('sha256').update(readFileSync(file)).digest('hex');}
function artifact(root:string,file:string,kind:BackupArtifact['kind']):BackupArtifact{return{path:path.relative(root,file).replaceAll('\\','/'),sha256:sha256(file),bytes:statSync(file).size,kind};}
function files(root:string):string[]{if(!existsSync(root))return[];return readdirSync(root,{withFileTypes:true}).flatMap(entry=>{const candidate=path.join(root,entry.name);return entry.isDirectory()?files(candidate):[candidate];});}
function backupRoot(config:PlatformConfig):string{return path.join(config.platformRoot,'data','backups');}
function encrypt(content:Buffer,passphrase:string):Buffer{if(passphrase.length<16)throw new Error('INVALID_BACKUP_PASSPHRASE');const salt=randomBytes(16);const iv=randomBytes(12);const key=scryptSync(passphrase,salt,32);const cipher=createCipheriv('aes-256-gcm',key,iv);const ciphertext=Buffer.concat([cipher.update(content),cipher.final()]);return Buffer.concat([MAGIC,salt,iv,cipher.getAuthTag(),ciphertext]);}
function decrypt(content:Buffer,passphrase:string):Buffer{if(!content.subarray(0,MAGIC.length).equals(MAGIC))throw new Error('INVALID_ENCRYPTED_BACKUP');if(!passphrase)throw new Error('BACKUP_PASSPHRASE_REQUIRED');const salt=content.subarray(MAGIC.length,MAGIC.length+16);const iv=content.subarray(MAGIC.length+16,MAGIC.length+28);const tag=content.subarray(MAGIC.length+28,MAGIC.length+44);const ciphertext=content.subarray(MAGIC.length+44);try{const decipher=createDecipheriv('aes-256-gcm',scryptSync(passphrase,salt,32),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(ciphertext),decipher.final()]);}catch{throw new Error('BACKUP_DECRYPTION_FAILED');}}

export function createDemoBackup(config:PlatformConfig=loadConfig(),now=new Date(),options:{encryptionPassphrase?:string}={}):{directory:string;manifest:BackupManifest}{
 assertDemoDatabasePath(config);if(!existsSync(config.databasePath))throw new Error('Banco DEMO inexistente para backup.');const database=openDatabase(config);try{database.exec('PRAGMA wal_checkpoint(TRUNCATE)');}finally{database.close();}
 const stamp=now.toISOString().replaceAll(':','-').replaceAll('.','-');const directory=path.join(backupRoot(config),stamp);mkdirSync(directory,{recursive:true});const databaseFile=path.join(directory,'platform-demo.sqlite');copyFileSync(config.databasePath,databaseFile);const metadataFile=path.join(directory,'metadata.json');writeFileSync(metadataFile,`${JSON.stringify({environment:config.environment,databaseDriver:config.databaseDriver,storageMode:config.storageMode,features:config.features,createdAt:now.toISOString()},null,2)}\n`,{encoding:'utf8',flag:'wx'});const documentTarget=path.join(directory,'documents');if(existsSync(config.storagePath))cpSync(config.storagePath,documentTarget,{recursive:true,errorOnExist:true});const documentFiles=files(documentTarget);const protectedFiles=[databaseFile,metadataFile,...documentFiles];const passphrase=options.encryptionPassphrase;if(passphrase)for(const file of protectedFiles)writeFileSync(file,encrypt(readFileSync(file),passphrase));const artifacts:BackupArtifact[]=[artifact(directory,databaseFile,'DATABASE'),artifact(directory,metadataFile,'METADATA'),...documentFiles.map(file=>artifact(directory,file,'DOCUMENT'))];const databaseArtifact=artifacts[0];if(!databaseArtifact)throw new Error('BACKUP_DATABASE_MISSING');const manifest:BackupManifest={version:2,environment:config.environment,createdAt:now.toISOString(),databaseFile:path.basename(databaseFile),sha256:databaseArtifact.sha256,bytes:databaseArtifact.bytes,productionBackup:false,artifacts,encrypted:Boolean(passphrase),encryptionAlgorithm:passphrase?'AES-256-GCM-SCRYPT':null,remoteReplication:'DISABLED_DEMO'};writeFileSync(path.join(directory,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`,{encoding:'utf8',flag:'wx'});return{directory,manifest};
}
export function listDemoBackups(config:PlatformConfig=loadConfig()):{directory:string;createdAt:string;artifacts:number;bytes:number;encrypted:boolean}[]{assertDemoDatabasePath(config);const root=backupRoot(config);if(!existsSync(root))return[];return readdirSync(root,{withFileTypes:true}).filter(item=>item.isDirectory()&&existsSync(path.join(root,item.name,'manifest.json'))).map(item=>{const directory=path.join(root,item.name);const manifest=JSON.parse(readFileSync(path.join(directory,'manifest.json'),'utf8')) as BackupManifest;return{directory,createdAt:manifest.createdAt,artifacts:manifest.artifacts.length,bytes:manifest.artifacts.reduce((total,entry)=>total+entry.bytes,0),encrypted:manifest.encrypted};}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export function applyDemoBackupRetention(keep:number,config:PlatformConfig=loadConfig()):string[]{assertDemoDatabasePath(config);if(!Number.isInteger(keep)||keep<1)throw new Error('INVALID_BACKUP_RETENTION');const expired=listDemoBackups(config).slice(keep);for(const item of expired)rmSync(item.directory,{recursive:true,force:true});return expired.map(item=>item.directory);}
export function testDemoRestore(directory:string,config:PlatformConfig=loadConfig(),options:{encryptionPassphrase?:string}={}):{ok:boolean;sha256:string;artifactsVerified:number;encrypted:boolean}{assertDemoDatabasePath(config);const manifest=JSON.parse(readFileSync(path.join(directory,'manifest.json'),'utf8')) as BackupManifest;for(const item of manifest.artifacts){const candidate=path.resolve(directory,item.path);const relative=path.relative(path.resolve(directory),candidate);if(relative.startsWith('..')||path.isAbsolute(relative)||!existsSync(candidate)||sha256(candidate)!==item.sha256||statSync(candidate).size!==item.bytes)throw new Error('Checksum do backup DEMO invalido.');}const source=path.join(directory,manifest.databaseFile);const restorePath=path.join(config.platformRoot,'data',`restore-test-${process.pid}.sqlite`);const sourceContent=readFileSync(source);writeFileSync(restorePath,manifest.encrypted?decrypt(sourceContent,options.encryptionPassphrase??''):sourceContent,{flag:'wx'});try{const database=new DatabaseSync(restorePath,{readOnly:true});try{const integrity=String(database.prepare('PRAGMA integrity_check').get()?.integrity_check??'unknown');return{ok:integrity==='ok',sha256:sha256(restorePath),artifactsVerified:manifest.artifacts.length,encrypted:manifest.encrypted};}finally{database.close();}}finally{if(existsSync(restorePath))rmSync(restorePath);}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const passphrase=process.env.PLATFORM_BACKUP_PASSPHRASE;const backup=createDemoBackup(loadConfig(),new Date(),passphrase?{encryptionPassphrase:passphrase}:{});console.log(JSON.stringify({directory:backup.directory,manifest:backup.manifest,restoreTest:testDemoRestore(backup.directory,loadConfig(),passphrase?{encryptionPassphrase:passphrase}:{})},null,2));}
