import { randomUUID } from 'node:crypto';import type { PlatformDatabase } from '../database/db.js';import { withTransaction } from '../database/db.js';import type { Principal } from './types.js';
const transitions:Readonly<Record<string,readonly string[]>>={REQUESTED:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['RECEIVED'],REJECTED:['CLOSED'],RECEIVED:['INSPECTED'],INSPECTED:['RESTOCKED','CLOSED'],RESTOCKED:['CLOSED'],CLOSED:[]};
function scoped(actor:Principal,companyId:unknown):void{if(actor.roles.includes('WHOLESALE')&&String(companyId)!==actor.companyId)throw new Error('RETURN_NOT_FOUND');}
function balance(database:PlatformDatabase,itemId:string):{physical:number;reserved:number}{const row=database.prepare('SELECT COALESCE(SUM(physical_delta),0) AS physical,COALESCE(SUM(reserved_delta),0) AS reserved FROM inventory_movements WHERE inventory_item_id=?').get(itemId);return{physical:Number(row?.physical),reserved:Number(row?.reserved)};}
export class InventoryLedgerService {
 constructor(private readonly database:PlatformDatabase) {}
 record(actor:Principal,input:{inventoryItemId:string;destinationInventoryItemId?:string;operationKind:string;quantity:number;targetPhysicalQuantity?:number;documentReference?:string|null;reason:string;comment?:string;origin?:string|null;destination?:string|null;referenceType:string;referenceId?:string|null},now=new Date()):object {
  const quantity=Number(input.quantity);if(!Number.isInteger(quantity)||quantity<0||quantity>10000||input.reason.trim().length<3)throw new Error('INVALID_LEDGER_MOVEMENT');
  const kind=input.operationKind.toUpperCase();const allowed=new Set(['ENTRY','RETURN','ADJUSTMENT_POSITIVE','ADJUSTMENT_NEGATIVE','CORRECTION','PHYSICAL_COUNT','CANCELLATION','RELEASE','SALE','RESERVATION','TRANSFER']);if(!allowed.has(kind))throw new Error('INVALID_LEDGER_MOVEMENT');
  const savepoint=`ledger_${randomUUID().replaceAll('-','')}`;this.database.exec(`SAVEPOINT ${savepoint}`);
  try{
   const sourceBefore=balance(this.database,input.inventoryItemId);let physicalDelta=0;let reservedDelta=0;let movementType='';
   if(kind==='ENTRY'||kind==='RETURN'||kind==='ADJUSTMENT_POSITIVE'){physicalDelta=quantity;movementType=kind==='ENTRY'?'RECEIPT':kind==='RETURN'?'RETURN':'ADJUSTMENT_IN';}
   else if(kind==='ADJUSTMENT_NEGATIVE'){physicalDelta=-quantity;movementType='ADJUSTMENT_OUT';}
   else if(kind==='RESERVATION'){reservedDelta=quantity;movementType='RESERVATION';}
   else if(kind==='RELEASE'||kind==='CANCELLATION'){reservedDelta=-quantity;movementType=kind;}
   else if(kind==='SALE'){physicalDelta=-quantity;reservedDelta=-quantity;movementType='SALE';}
   else if(kind==='CORRECTION'||kind==='PHYSICAL_COUNT'){const target=input.targetPhysicalQuantity??(kind==='PHYSICAL_COUNT'?quantity:sourceBefore.physical+quantity);if(!Number.isInteger(target)||target<0||target>100000)throw new Error('INVALID_LEDGER_MOVEMENT');physicalDelta=target-sourceBefore.physical;movementType=physicalDelta<0?'ADJUSTMENT_OUT':'ADJUSTMENT_IN';}
   else {physicalDelta=-quantity;movementType='TRANSFER';if(!input.destinationInventoryItemId||input.destinationInventoryItemId===input.inventoryItemId)throw new Error('INVALID_LEDGER_TRANSFER');}
   const sourceAfter={physical:sourceBefore.physical+physicalDelta,reserved:sourceBefore.reserved+reservedDelta};if(sourceAfter.physical<0||sourceAfter.reserved<0||sourceAfter.reserved>sourceAfter.physical)throw new Error('INSUFFICIENT_INVENTORY');
   const sourceId=this.insert(actor,input.inventoryItemId,kind,movementType,physicalDelta,reservedDelta,input,sourceBefore,sourceAfter,now);
   let destinationMovementId:string|null=null;let destinationBalance:null|{before:{physical:number;reserved:number};after:{physical:number;reserved:number}}=null;
   if(kind==='TRANSFER'&&input.destinationInventoryItemId){const destinationBefore=balance(this.database,input.destinationInventoryItemId);if(!this.database.prepare('SELECT id FROM inventory_items WHERE id=?').get(input.destinationInventoryItemId))throw new Error('INVALID_LEDGER_TRANSFER');const destinationAfter={physical:destinationBefore.physical+quantity,reserved:destinationBefore.reserved};destinationMovementId=this.insert(actor,input.destinationInventoryItemId,kind,'TRANSFER',quantity,0,{...input,origin:input.destination??null,destination:input.origin??null,referenceId:sourceId},destinationBefore,destinationAfter,now);destinationBalance={before:destinationBefore,after:destinationAfter};}
   this.database.exec(`RELEASE SAVEPOINT ${savepoint}`);return{id:sourceId,destinationMovementId,before:sourceBefore,after:sourceAfter,destinationBalance,immutable:true};
  }catch(error){this.database.exec(`ROLLBACK TO SAVEPOINT ${savepoint}`);this.database.exec(`RELEASE SAVEPOINT ${savepoint}`);throw error;}
 }
 private insert(actor:Principal,itemId:string,kind:string,movementType:string,physicalDelta:number,reservedDelta:number,input:{documentReference?:string|null;reason:string;comment?:string;origin?:string|null;destination?:string|null;referenceType:string;referenceId?:string|null},before:{physical:number;reserved:number},after:{physical:number;reserved:number},now:Date):string {
  if(!this.database.prepare('SELECT id FROM inventory_items WHERE id=?').get(itemId))throw new Error('INVALID_LEDGER_MOVEMENT');const id=randomUUID();this.database.prepare('INSERT INTO inventory_movements (id,inventory_item_id,movement_type,physical_delta,reserved_delta,reference_type,reference_id,notes,actor_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,itemId,movementType,physicalDelta,reservedDelta,input.referenceType,input.referenceId??null,input.comment?.trim()||input.reason.trim(),actor.userId,now.toISOString());this.database.prepare('INSERT INTO inventory_movement_details (movement_id,operation_kind,document_reference,reason,comment,origin_location,destination_location,physical_before,physical_after,reserved_before,reserved_after) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,kind,input.documentReference??null,input.reason.trim(),input.comment?.trim()??'',input.origin??null,input.destination??null,before.physical,after.physical,before.reserved,after.reserved);return id;
 }
}
export class AfterSalesService{private readonly ledger:InventoryLedgerService;constructor(private readonly database:PlatformDatabase){this.ledger=new InventoryLedgerService(database);}create(actor:Principal,input:{orderId:string;reasonCode:string;notes:string;items:{orderItemId:string;quantity:number}[]},now=new Date()):object{return withTransaction(this.database,()=>{const order=this.database.prepare("SELECT id,company_id,status FROM orders WHERE id=? AND status IN ('DELIVERED','RETURNED')").get(input.orderId);if(!order)throw new Error('ORDER_NOT_RETURNABLE');scoped(actor,order.company_id);if(input.reasonCode.trim().length<3||input.notes.trim().length<3||input.items.length<1)throw new Error('INVALID_RETURN');const id=randomUUID();const number=`RET-DEMO-${String(Number(this.database.prepare('SELECT COUNT(*) AS total FROM return_requests').get()?.total)+1).padStart(5,'0')}`;this.database.prepare("INSERT INTO return_requests (id,return_number,order_id,company_id,status,reason_code,customer_notes,internal_notes,requested_by_user_id,created_at,updated_at) VALUES (?,?,?,?,'REQUESTED',?,?,'',?,?,?)").run(id,number,input.orderId,order.company_id?String(order.company_id):null,input.reasonCode.trim(),input.notes.trim(),actor.userId,now.toISOString(),now.toISOString());for(const item of input.items){const row=this.database.prepare('SELECT oi.id,oi.quantity,ii.id AS inventory_item_id FROM order_items oi JOIN inventory_items ii ON ii.variant_id=oi.variant_id WHERE oi.id=? AND oi.order_id=?').get(item.orderItemId,input.orderId);const prior=Number(this.database.prepare('SELECT COALESCE(SUM(ri.quantity),0) AS quantity FROM return_items ri JOIN return_requests rr ON rr.id=ri.return_id WHERE ri.order_item_id=? AND rr.status<>\'REJECTED\'').get(item.orderItemId)?.quantity);if(!row||!Number.isInteger(item.quantity)||item.quantity<1||prior+item.quantity>Number(row.quantity))throw new Error('INVALID_RETURN_ITEM');this.database.prepare('INSERT INTO return_items (id,return_id,order_item_id,inventory_item_id,quantity) VALUES (?,?,?,?,?)').run(randomUUID(),id,item.orderItemId,String(row.inventory_item_id),item.quantity);}this.history(id,null,'REQUESTED','Solicitação DEMO criada.',actor,now);return{id,returnNumber:number,status:'REQUESTED'};});}
 list(actor:Principal):object{const companyId=actor.roles.includes('WHOLESALE')?actor.companyId:null;return{returns:this.database.prepare(`SELECT rr.*,o.order_number,u.display_name AS requested_by_name,COUNT(ri.id) AS item_count,SUM(ri.quantity) AS total_quantity FROM return_requests rr JOIN orders o ON o.id=rr.order_id LEFT JOIN users u ON u.id=rr.requested_by_user_id LEFT JOIN return_items ri ON ri.return_id=rr.id WHERE (? IS NULL OR rr.company_id=?) GROUP BY rr.id ORDER BY rr.updated_at DESC`).all(companyId,companyId),environment:'DEMO',warrantyPromise:false};} transition(actor:Principal,id:string,input:{status:string;notes:string;resolution?:string;inspectionResult?:string},now=new Date()):object{return withTransaction(this.database,()=>{const row=this.database.prepare('SELECT * FROM return_requests WHERE id=?').get(id);if(!row)throw new Error('RETURN_NOT_FOUND');scoped(actor,row.company_id);if(actor.roles.includes('WHOLESALE'))throw new Error('FORBIDDEN:return.review');const from=String(row.status);const to=input.status.toUpperCase();if(!(transitions[from]??[]).includes(to)||input.notes.trim().length<2)throw new Error('INVALID_RETURN_STATUS');if(to==='INSPECTED'){const resolution=(input.resolution??'').toUpperCase();if(!['RESTOCK','DISCARD','REPAIR','INTERNAL_REFUND'].includes(resolution))throw new Error('INVALID_RETURN_STATUS');this.database.prepare('UPDATE return_requests SET resolution=? WHERE id=?').run(resolution,id);this.database.prepare('UPDATE return_items SET inspection_result=? WHERE return_id=?').run((input.inspectionResult??resolution).slice(0,300),id);}if(to==='RESTOCKED'){if(String(row.resolution)!=='RESTOCK')throw new Error('INVALID_RETURN_STATUS');for(const item of this.database.prepare('SELECT inventory_item_id,quantity FROM return_items WHERE return_id=?').all(id)){this.ledger.record(actor,{inventoryItemId:String(item.inventory_item_id),operationKind:'RETURN',quantity:Number(item.quantity),documentReference:String(row.return_number),reason:'Devolução aprovada e inspecionada',comment:input.notes,origin:'PÓS-VENDA',destination:'ESTOQUE DEMO',referenceType:'RETURN',referenceId:id},now);}this.database.prepare("UPDATE orders SET status='RETURNED',payment_status='REFUNDED',updated_at=? WHERE id=?").run(now.toISOString(),String(row.order_id));}this.database.prepare('UPDATE return_requests SET status=?,internal_notes=?,updated_at=? WHERE id=?').run(to,input.notes.trim(),now.toISOString(),id);this.history(id,from,to,input.notes,actor,now);return{id,fromStatus:from,toStatus:to};});}
 private history(id:string,from:string|null,to:string,notes:string,actor:Principal,now:Date):void{this.database.prepare('INSERT INTO return_history (id,return_id,from_status,to_status,notes,actor_user_id,created_at) VALUES (?,?,?,?,?,?,?)').run(randomUUID(),id,from,to,notes,actor.userId,now.toISOString());}}
export function operationTimeline(database:PlatformDatabase,actor:Principal,orderId:string):object {
 const order=database.prepare('SELECT * FROM orders WHERE id=?').get(orderId);if(!order)throw new Error('ORDER_NOT_FOUND');scoped(actor,order.company_id);const quoteId=order.quote_id?String(order.quote_id):null;const companyId=order.company_id?String(order.company_id):null;const customerId=order.customer_id?String(order.customer_id):null;
 const quote=quoteId?database.prepare('SELECT * FROM quotes WHERE id=?').get(quoteId):null;const orderItems=database.prepare('SELECT oi.*,p.model_name,v.capacity,v.color FROM order_items oi JOIN product_variants v ON v.id=oi.variant_id JOIN products p ON p.id=v.product_id WHERE oi.order_id=?').all(orderId);const reservations=database.prepare('SELECT * FROM reservations WHERE order_id=? ORDER BY created_at').all(orderId);const reservationIds=reservations.map(row=>String(row.id));const shipments=database.prepare('SELECT * FROM shipments WHERE order_id=? ORDER BY created_at').all(orderId);const returns=database.prepare('SELECT * FROM return_requests WHERE order_id=? ORDER BY created_at').all(orderId);const returnIds=returns.map(row=>String(row.id));
 const conversations=database.prepare('SELECT * FROM conversations WHERE (? IS NOT NULL AND company_id=?) OR (? IS NOT NULL AND customer_id=?) ORDER BY created_at').all(companyId,companyId,customerId,customerId);const conversationIds=conversations.map(row=>String(row.id));const messages=conversationIds.length?database.prepare(`SELECT * FROM messages WHERE conversation_id IN (${conversationIds.map(()=>'?').join(',')}) ${actor.roles.includes('WHOLESALE')?"AND message_type<>'INTERNAL_NOTE'":''} ORDER BY created_at`).all(...conversationIds):[];const messageIds=messages.map(row=>String(row.id));const documentClauses=['(entity_type=\'ORDER\' AND entity_id=?)'];const documentArgs:string[]=[orderId];if(companyId){documentClauses.push("(entity_type='COMPANY' AND entity_id=?)");documentArgs.push(companyId);}if(messageIds.length){documentClauses.push(`(entity_type='MESSAGE' AND entity_id IN (${messageIds.map(()=>'?').join(',')}))`);documentArgs.push(...messageIds);}const documents=database.prepare(`SELECT id,company_id,entity_type,entity_id,original_name,mime_type,size_bytes,checksum_sha256,scan_status,expires_at,created_at FROM documents WHERE deleted_at IS NULL AND (${documentClauses.join(' OR ')}) ORDER BY created_at`).all(...documentArgs);
 const audits=database.prepare("SELECT * FROM audit_events WHERE (entity_type='ORDER' AND entity_id=?) OR (? IS NOT NULL AND entity_type='QUOTE' AND entity_id=?) OR (entity_type='SHIPMENT' AND entity_id IN (SELECT id FROM shipments WHERE order_id=?))").all(orderId,quoteId,quoteId,orderId);const inventoryMovements=reservationIds.length?database.prepare(`SELECT m.*,d.operation_kind,d.document_reference,d.reason,d.origin_location,d.destination_location,d.physical_before,d.physical_after,d.reserved_before,d.reserved_after FROM inventory_movements m LEFT JOIN inventory_movement_details d ON d.movement_id=m.id WHERE (m.reference_type='ORDER' AND m.reference_id=?) OR m.reference_id IN (${reservationIds.map(()=>'?').join(',')}) ORDER BY m.created_at`).all(orderId,...reservationIds):database.prepare("SELECT m.*,d.operation_kind,d.document_reference,d.reason,d.origin_location,d.destination_location,d.physical_before,d.physical_after,d.reserved_before,d.reserved_after FROM inventory_movements m LEFT JOIN inventory_movement_details d ON d.movement_id=m.id WHERE m.reference_type='ORDER' AND m.reference_id=? ORDER BY m.created_at").all(orderId);
 const events=[{type:'ORDER',at:order.created_at,data:order},...(quote?[{type:'QUOTE',at:quote.created_at,data:quote}]:[]),...conversations.map(data=>({type:'CONVERSATION',at:data.created_at,data})),...messages.map(data=>({type:'MESSAGE',at:data.created_at,data})),...documents.map(data=>({type:'DOCUMENT',at:data.created_at,data})),...reservations.map(data=>({type:'RESERVATION',at:data.created_at,data})),...inventoryMovements.map(data=>({type:'INVENTORY',at:data.created_at,data})),...shipments.map(data=>({type:'SHIPMENT',at:data.created_at,data})),...audits.map(data=>({type:'AUDIT',at:data.created_at,data})),...returns.map(data=>({type:'RETURN',at:data.created_at,data})),...(returnIds.length?database.prepare(`SELECT * FROM return_history WHERE return_id IN (${returnIds.map(()=>'?').join(',')})`).all(...returnIds).map(data=>({type:'RETURN_HISTORY',at:data.created_at,data})):[])].sort((a,b)=>String(a.at).localeCompare(String(b.at)));
 const totals=orderItems.reduce((sum,row)=>sum+Number(row.quantity)*Number(row.unit_price_cents),0);return{orderId,quoteId,companyId,paymentMode:'INTERNAL_STATUS_ONLY',summary:{values:{currency:order.currency,itemsCents:totals},responsibleUserId:order.assigned_user_id??null,deadlines:{quoteExpiresAt:quote?.expires_at??null,reservationExpiresAt:reservations.map(row=>row.expires_at).filter(Boolean)},stock:{reservations:reservations.length,movements:inventoryMovements.length},logistics:{deliveryMethod:order.delivery_method,shipments:shipments.length}},items:orderItems,events};
}