import { randomUUID } from 'node:crypto';import type { PlatformDatabase } from '../database/db.js';import { withTransaction } from '../database/db.js';import type { Principal } from './types.js';
const states=new Set(['NEW','OPEN','WAITING_CUSTOMER','WAITING_INTERNAL','RESOLVED','CLOSED']);const priorities=new Set(['LOW','NORMAL','HIGH','URGENT']);
function scope(actor:Principal,companyId:unknown):void{if(actor.roles.includes('WHOLESALE')&&String(companyId)!==actor.companyId)throw new Error('INBOX_NOT_FOUND');}
export class UnifiedInboxService{
 constructor(private readonly database:PlatformDatabase){}
 ensure(conversationId:string,now=new Date()):void{this.database.prepare("INSERT OR IGNORE INTO inbox_cases (conversation_id,status,priority,tags_json,updated_at) VALUES (?,'NEW','NORMAL','[]',?)").run(conversationId,now.toISOString());}
 list(actor:Principal,input:{search?:string;status?:string;priority?:string;assignedUserId?:string}={}):object{const companyId=actor.roles.includes('WHOLESALE')?actor.companyId:null;const search=`%${(input.search??'').trim().slice(0,100)}%`;const rows=this.database.prepare(`SELECT c.id,c.company_id,c.subject,ic.status,ic.priority,ic.assigned_user_id,ic.tags_json,ic.sla_due_at,ic.updated_at,COUNT(m.id) AS message_count FROM conversations c JOIN inbox_cases ic ON ic.conversation_id=c.id LEFT JOIN messages m ON m.conversation_id=c.id WHERE (? IS NULL OR c.company_id=?) AND (?='' OR c.subject LIKE ?) AND (?='' OR ic.status=?) AND (?='' OR ic.priority=?) AND (?='' OR ic.assigned_user_id=?) GROUP BY c.id ORDER BY CASE ic.priority WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'NORMAL' THEN 3 ELSE 4 END,COALESCE(ic.sla_due_at,'9999'),ic.updated_at DESC`).all(companyId,companyId,input.search?.trim()??'',search,input.status??'',input.status??'',input.priority??'',input.priority??'',input.assignedUserId??'',input.assignedUserId??'');return{cases:rows,environment:'DEMO',channels:['PLATFORM','EMAIL_FUTURE','WHATSAPP_FUTURE']};}
 update(actor:Principal,conversationId:string,input:{status?:string;priority?:string;assignedUserId?:string|null;tags?:string[];slaDueAt?:string|null},now=new Date()):object{return withTransaction(this.database,()=>{const conversation=this.database.prepare('SELECT company_id FROM conversations WHERE id=?').get(conversationId);if(!conversation)throw new Error('INBOX_NOT_FOUND');scope(actor,conversation.company_id);if(actor.roles.includes('WHOLESALE')&&(input.assignedUserId!==undefined||input.priority!==undefined||input.tags!==undefined||input.slaDueAt!==undefined))throw new Error('FORBIDDEN:inbox.manage');this.ensure(conversationId,now);const before=this.database.prepare('SELECT * FROM inbox_cases WHERE conversation_id=?').get(conversationId);const status=(input.status??String(before?.status)).toUpperCase();const priority=(input.priority??String(before?.priority)).toUpperCase();if(!states.has(status)||!priorities.has(priority)||input.slaDueAt&&Number.isNaN(Date.parse(input.slaDueAt)))throw new Error('INVALID_INBOX_CASE');if(input.assignedUserId&&!this.database.prepare("SELECT id FROM users WHERE id=? AND status='ACTIVE'").get(input.assignedUserId))throw new Error('INVALID_INBOX_CASE');const tags=JSON.stringify((input.tags??JSON.parse(String(before?.tags_json??'[]')) as string[]).map(tag=>tag.trim().slice(0,30)).filter(Boolean).slice(0,10));const assignedUserId=input.assignedUserId===undefined?(before?.assigned_user_id??null):input.assignedUserId;const slaDueAt=input.slaDueAt===undefined?(before?.sla_due_at??null):input.slaDueAt;this.database.prepare(`UPDATE inbox_cases SET status=?,priority=?,assigned_user_id=?,tags_json=?,sla_due_at=?,resolved_at=CASE WHEN ?='RESOLVED' THEN ? WHEN ?<>'RESOLVED' THEN NULL ELSE resolved_at END,updated_at=? WHERE conversation_id=?`).run(status,priority,assignedUserId,tags,slaDueAt,status,now.toISOString(),status,now.toISOString(),conversationId);this.database.prepare('UPDATE conversations SET assigned_user_id=?,status=?,updated_at=? WHERE id=?').run(assignedUserId,status==='CLOSED'?'CLOSED':status==='WAITING_CUSTOMER'||status==='WAITING_INTERNAL'?'PENDING':'OPEN',now.toISOString(),conversationId);const after=this.database.prepare('SELECT * FROM inbox_cases WHERE conversation_id=?').get(conversationId);this.database.prepare('INSERT INTO inbox_history (id,conversation_id,actor_user_id,action,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?)').run(randomUUID(),conversationId,actor.userId,'CASE_UPDATED',JSON.stringify(before),JSON.stringify(after),now.toISOString());return after??{};});}
 history(actor:Principal,conversationId:string):object{const conversation=this.database.prepare('SELECT company_id FROM conversations WHERE id=?').get(conversationId);if(!conversation)throw new Error('INBOX_NOT_FOUND');scope(actor,conversation.company_id);return{history:this.database.prepare('SELECT id,actor_user_id,action,before_json,after_json,created_at FROM inbox_history WHERE conversation_id=? ORDER BY created_at').all(conversationId)};}
}
