import { createDecipheriv, createHash, createHmac, timingSafeEqual } from 'node:crypto';
import type { PlatformDatabase } from '../database/db.js';
import type { PlatformConfig } from '../src/config.js';
function digest(config:PlatformConfig,value:string):string{return createHash('sha256').update(`${config.sessionSecret}:${value.trim().toUpperCase()}`).digest('hex');}
function decodeBase32(input:string):Buffer{const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0;const output:number[]=[];for(const char of input.replaceAll('=','').toUpperCase()){const index=alphabet.indexOf(char);if(index<0)throw new Error('INVALID_TOTP_SECRET');value=(value<<5)|index;bits+=5;if(bits>=8){output.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(output);}
function decrypt(config:PlatformConfig,value:string):string{const [iv,tag,encrypted]=value.split('.');if(!iv||!tag||!encrypted)throw new Error('INVALID_MFA_SECRET');const key=createHash('sha256').update(`mfa:${config.sessionSecret}`).digest();const decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(encrypted,'base64url')),decipher.final()]).toString('utf8');}
export function totpCode(secret:string,now=new Date(),offsetSteps=0):string{const counter=Math.floor(now.getTime()/30_000)+offsetSteps;const bytes=Buffer.alloc(8);bytes.writeBigUInt64BE(BigInt(counter));const mac=createHmac('sha1',decodeBase32(secret)).update(bytes).digest();const offset=(mac[19]??0)&15;const code=(((mac[offset]??0)&127)<<24)|((mac[offset+1]??0)<<16)|((mac[offset+2]??0)<<8)|(mac[offset+3]??0);return String(code%1_000_000).padStart(6,'0');}
function equal(left:string,right:string):boolean{const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);}
export function mfaEnabled(database:PlatformDatabase,userId:string):boolean{return Number(database.prepare('SELECT enabled FROM mfa_credentials WHERE user_id=?').get(userId)?.enabled??0)===1;}
export function verifyMfa(database:PlatformDatabase,config:PlatformConfig,userId:string,code:string,now=new Date()):'TOTP'|'RECOVERY'{const normalized=code.trim().toUpperCase();const row=database.prepare('SELECT secret_ciphertext,enabled FROM mfa_credentials WHERE user_id=?').get(userId) as {secret_ciphertext:string;enabled:number}|undefined;if(!row||row.enabled!==1)throw new Error('MFA_NOT_ENABLED');const secret=decrypt(config,row.secret_ciphertext);if([-1,0,1].some((step)=>equal(totpCode(secret,now,step),normalized)))return'TOTP';const recovery=database.prepare('SELECT id,code_hash FROM mfa_recovery_codes WHERE user_id=? AND used_at IS NULL').all(userId).find((item)=>equal(String(item.code_hash),digest(config,normalized)));if(!recovery)throw new Error('INVALID_MFA_CODE');database.prepare('UPDATE mfa_recovery_codes SET used_at=? WHERE id=? AND used_at IS NULL').run(now.toISOString(),String(recovery.id));return'RECOVERY';}
export function decryptedSecret(database:PlatformDatabase,config:PlatformConfig,userId:string):string{const row=database.prepare('SELECT secret_ciphertext FROM mfa_credentials WHERE user_id=?').get(userId) as {secret_ciphertext:string}|undefined;if(!row)throw new Error('MFA_NOT_STARTED');return decrypt(config,row.secret_ciphertext);}
