import { appendFileSync,mkdirSync } from 'node:fs';import path from 'node:path';import { randomUUID } from 'node:crypto';import type { PlatformDatabase } from '../database/db.js';import type { PlatformConfig } from '../src/config.js';import type { StorageProvider } from './documents.js';import type { DeliveryProvider } from './integrations.js';import type { Principal } from './types.js';
const secretKeys=/secret|password|token|authorization|cookie/i;function redact(value:unknown):unknown{if(Array.isArray(value))return value.map(redact);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,secretKeys.test(key)?'[REDACTED]':redact(item)]));return value;}
export class StructuredLogger{constructor(private readonly config:PlatformConfig){}write(level:'INFO'|'WARN'|'ERROR',event:string,context:Record<string,unknown>={}):void{const entry={timestamp:new Date().toISOString(),level,event,environment:this.config.environment,...redact(context) as object};if(this.config.demo){mkdirSync(this.config.logPath,{recursive:true});appendFileSync(path.join(this.config.logPath,'platform.jsonl'),`${JSON.stringify(entry)}\n`,{encoding:'utf8'});}}}
class Metrics{private requests=0;private errors=0;private logins=0;private totalDuration=0;observe(status:number,duration:number,pathName:string):void{this.requests+=1;this.totalDuration+=duration;if(status>=500)this.errors+=1;if(pathName==='/api/auth/login'&&status<400)this.logins+=1;}snapshot(database:PlatformDatabase):object{return{requestsTotal:this.requests,errorsTotal:this.errors,loginsTotal:this.logins,averageRequestDurationMs:this.requests?Math.round(this.totalDuration/this.requests):0,pendingDeliveries:Number(database.prepare("SELECT COUNT(*) AS total FROM delivery_outbox WHERE status IN ('PENDING','FAILED')").get()?.total),pendingJobs:Number(database.prepare("SELECT COUNT(*) AS total FROM job_queue WHERE status='PENDING'").get()?.total),failedJobs:Number(database.prepare("SELECT COUNT(*) AS total FROM job_queue WHERE status IN ('FAILED','DEAD_LETTER')").get()?.total)};}}
export const platformMetrics=new Metrics();
export function observeRequest(status:number,duration:number,pathName:string):void{platformMetrics.observe(status,duration,pathName);}
export function operationalHealth(database:PlatformDatabase,config:PlatformConfig,storage:StorageProvider,providers:Readonly<Record<'EMAIL'|'WHATSAPP',DeliveryProvider>>):object{let databaseReady=false;try{databaseReady=Number(database.prepare('SELECT 1 AS ok').get()?.ok)===1;}catch{databaseReady=false;}const status={environment:config.environment,database:{ready:databaseReady,driver:config.databaseDriver},storage:storage.health(),email:providers.EMAIL.health(),whatsapp:providers.WHATSAPP.health(),features:config.features,metrics:platformMetrics.snapshot(database)};return{ready:databaseReady&&storage.health().ready,status};}
export type JobHandler=(payload:Readonly<Record<string,unknown>>)=>void;
export class LocalJobQueue{constructor(private readonly database:PlatformDatabase,private readonly handlers:Readonly<Record<string,JobHandler>>){}enqueue(actor:Principal|null,jobType:string,payload:Readonly<Record<string,unknown>>,options:{correlationId?:string;maxAttempts?:number;runAfter?:Date}={},now=new Date()):object{if(!['EMAIL_DELIVERY','WHATSAPP_DELIVERY','EXPIRE_RESERVATIONS','NOTIFICATIONS','REPORT','SESSION_CLEANUP','DOCUMENT_PROCESSING','BACKUP'].includes(jobType))throw new Error('INVALID_JOB');const id=randomUUID();const runAfter=(options.runAfter??now).toISOString();this.database.prepare("INSERT INTO job_queue (id,job_type,payload_json,correlation_id,status,max_attempts,run_after,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,'PENDING',?,?,?,?,?)").run(id,jobType,JSON.stringify(payload),options.correlationId??null,options.maxAttempts??3,runAfter,actor?.userId??null,now.toISOString(),now.toISOString());return{id,status:'PENDING'};}
 runNext(now=new Date()):object|null{const job=this.database.prepare("SELECT * FROM job_queue WHERE status IN ('PENDING','FAILED') AND attempts<max_attempts AND run_after<=? ORDER BY created_at LIMIT 1").get(now.toISOString());if(!job)return null;const id=String(job.id);const attempt=Number(job.attempts)+1;this.database.prepare("UPDATE job_queue SET status='RUNNING',attempts=?,locked_at=?,updated_at=? WHERE id=?").run(attempt,now.toISOString(),now.toISOString(),id);try{const handler=this.handlers[String(job.job_type)];if(!handler)throw new Error('JOB_HANDLER_NOT_CONFIGURED');handler(JSON.parse(String(job.payload_json)) as Record<string,unknown>);this.database.prepare("UPDATE job_queue SET status='COMPLETED',completed_at=?,last_error=NULL,updated_at=? WHERE id=?").run(now.toISOString(),now.toISOString(),id);this.attempt(id,attempt,'COMPLETED',null,now);return{id,status:'COMPLETED',attempt};}catch(error){const message=(error instanceof Error?error.message:'JOB_FAILED').slice(0,240);const terminal=attempt>=Number(job.max_attempts);this.database.prepare('UPDATE job_queue SET status=?,last_error=?,run_after=?,updated_at=? WHERE id=?').run(terminal?'DEAD_LETTER':'FAILED',message,new Date(now.getTime()+attempt*60_000).toISOString(),now.toISOString(),id);this.attempt(id,attempt,'FAILED',message,now);return{id,status:terminal?'DEAD_LETTER':'FAILED',attempt};}}
 list():object{return{jobs:this.database.prepare('SELECT id,job_type,status,attempts,max_attempts,run_after,last_error,created_at,updated_at FROM job_queue ORDER BY created_at DESC LIMIT 200').all(),adapter:'LOCAL_DETERMINISTIC_DEMO'};}private attempt(jobId:string,attempt:number,status:string,error:string|null,now:Date):void{this.database.prepare('INSERT INTO job_attempts (id,job_id,attempt_number,status,error_message,started_at,finished_at) VALUES (?,?,?,?,?,?,?)').run(randomUUID(),jobId,attempt,status,error,now.toISOString(),now.toISOString());}}
export class ExternalQueueAdapter{enqueue():never{throw new Error('EXTERNAL_QUEUE_NOT_PROVISIONED');}}
