import { randomUUID } from 'node:crypto';import { fileURLToPath } from 'node:url';import path from 'node:path';import type { PlatformDatabase } from '../database/db.js';import { persistenceAdapter,type PersistenceAdapter } from '../database/persistence.js';import { hashPassword } from '../server/password.js';import { loadConfig,type PlatformConfig } from './config.js';
const permissions=['users.read','users.write','settings.read','settings.write','audit.read','reports.read','catalog.read','catalog.write','prices.read','prices.write','inventory.read','inventory.write','customers.read','customers.write','companies.read','companies.approve','quotes.read','quotes.write','orders.read','orders.write','requests.read','requests.write','messages.read','messages.write'] as const;
export function bootstrapFirstAdmin(database:PlatformDatabase,config:PlatformConfig,input:{confirmation:string;email:string;displayName:string;temporaryPassword:string},now=new Date()):object{if(config.environment!=='PRODUCTION'||config.databaseDriver!=='external')throw new Error('BOOTSTRAP_PRODUCTION_ONLY');if(input.confirmation!=='CREATE FIRST CELULARS ADMIN')throw new Error('BOOTSTRAP_CONFIRMATION_REQUIRED');const email=input.email.trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||input.displayName.trim().length<2)throw new Error('INVALID_BOOTSTRAP_ADMIN');if(database.prepare("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.code='ADMIN'").get())throw new Error('ADMIN_ALREADY_EXISTS');const password=hashPassword(input.temporaryPassword);const userId=randomUUID();database.exec('BEGIN IMMEDIATE');try{const roleId='role-production-admin';database.prepare("INSERT OR IGNORE INTO roles (id,code,name,created_at) VALUES (?,'ADMIN','Administrador',?)").run(roleId,now.toISOString());for(const [index,code]of permissions.entries()){const permissionId=`permission-production-${String(index+1).padStart(4,'0')}`;database.prepare('INSERT OR IGNORE INTO permissions (id,code,description,created_at) VALUES (?,?,?,?)').run(permissionId,code,`Permissão ${code}`,now.toISOString());const permission=database.prepare('SELECT id FROM permissions WHERE code=?').get(code);database.prepare('INSERT OR IGNORE INTO role_permissions (role_id,permission_id) VALUES (?,?)').run(roleId,String(permission?.id));}database.prepare("INSERT INTO users (id,email,display_name,password_hash,password_salt,status,must_change_password,created_at,updated_at) VALUES (?,?,?,?,?,'ACTIVE',1,?,?)").run(userId,email,input.displayName.trim(),password.hash,password.salt,now.toISOString(),now.toISOString());database.prepare('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)').run(userId,roleId);database.prepare('INSERT INTO audit_events (id,actor_user_id,action,entity_type,entity_id,after_json,ip_address,user_agent,created_at) VALUES (?,NULL,\'BOOTSTRAP_ADMIN\',\'USER\',?,? ,\'LOCAL_CLI\',\'platform:bootstrap-admin\',?)').run(randomUUID(),userId,JSON.stringify({email,mustChangePassword:true,mfaRecommended:true}),now.toISOString());database.exec('COMMIT');return{userId,email,mustChangePassword:true,mfaRecommended:true};}catch(error){database.exec('ROLLBACK');throw error;}}
export function bootstrapAdminCli(source:NodeJS.ProcessEnv=process.env,config:PlatformConfig=loadConfig(),adapter:PersistenceAdapter=persistenceAdapter(config)):object{
 if(config.environment!=='PRODUCTION'||config.databaseDriver!=='external')throw new Error('BOOTSTRAP_PRODUCTION_ONLY');
 const input={confirmation:source.PLATFORM_BOOTSTRAP_CONFIRMATION??'',email:source.PLATFORM_BOOTSTRAP_EMAIL??'',displayName:source.PLATFORM_BOOTSTRAP_DISPLAY_NAME??'',temporaryPassword:source.PLATFORM_BOOTSTRAP_TEMPORARY_PASSWORD??''};
 if(!input.confirmation||!input.email||!input.displayName||!input.temporaryPassword)throw new Error('BOOTSTRAP_PARAMETERS_REQUIRED');
 const database=adapter.open();try{return bootstrapFirstAdmin(database,config,input);}finally{database.close();}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{console.log(JSON.stringify(bootstrapAdminCli(),null,2));}catch(error){console.error(error instanceof Error?error.message:'BOOTSTRAP_FAILED');process.exitCode=2;}}
