import assert from 'node:assert/strict';
import { existsSync,rmSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { openDatabase } from '../database/db.js';
import { migrateDatabase } from '../database/migrate.js';
import { seedDatabase } from '../database/seed.js';
import { UserAdministrationService } from '../server/admin-users.js';
import { AuthService } from '../server/auth.js';
import { loadConfig } from '../src/config.js';
import type { Principal } from '../server/types.js';
function remove(file:string):void{for(const item of[file,`${file}-wal`,`${file}-shm`])if(existsSync(item))rmSync(item);}
function admin():Principal{return{sessionId:'admin-session',userId:'user-demo-admin',email:'admin@demo.invalid',displayName:'Admin',companyId:'company-demo-internal',roles:['ADMIN'],permissions:['users.read','users.write'],csrfToken:'csrf'};}
test('user administration protects the final admin and records confirmed critical changes',()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`user-admin-test-${process.pid}.sqlite`);const config=loadConfig({databasePath});remove(databasePath);const database=openDatabase(config);try{migrateDatabase(database);seedDatabase(database,config,'Admin-User-Test-Password!');const service=new UserAdministrationService(database);assert.throws(()=>service.update(admin(),'user-demo-admin',{roleIds:['role-employee'],confirmSelfCriticalChange:true}),/LAST_ADMIN_REQUIRED/);service.update(admin(),'user-employee-demo-0001',{roleIds:['role-admin']});assert.throws(()=>service.update(admin(),'user-demo-admin',{roleIds:['role-employee']}),/SELF_CRITICAL_CONFIRMATION_REQUIRED/);service.update(admin(),'user-demo-admin',{roleIds:['role-employee'],confirmSelfCriticalChange:true});assert.equal((service.history(admin(),'user-demo-admin') as {history:unknown[]}).history.length,1);}finally{database.close();remove(databasePath);}});
test('suspension, expiry and permission overrides affect active access',()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`user-access-test-${process.pid}.sqlite`);const config=loadConfig({databasePath});remove(databasePath);const database=openDatabase(config);try{migrateDatabase(database);seedDatabase(database,config,'Admin-User-Test-Password!');const service=new UserAdministrationService(database);const auth=new AuthService(database,config);const login=auth.login('funcionario1@demo.invalid','Admin-User-Test-Password!',{ipAddress:'127.0.0.1',userAgent:'test'});service.update(admin(),'user-employee-demo-0001',{roleIds:['role-employee'],permissions:[{code:'catalog.read',effect:'DENY'}]});assert.equal(auth.authenticate(login.token)?.permissions.includes('catalog.read'),false);service.update(admin(),'user-employee-demo-0001',{status:'SUSPENDED'});assert.equal(auth.authenticate(login.token),null);service.update(admin(),'user-employee-demo-0002',{accessExpiresAt:'2026-07-19T00:00:00.000Z'},new Date('2026-07-18T00:00:00.000Z'));assert.throws(()=>auth.login('funcionario2@demo.invalid','Admin-User-Test-Password!',{ipAddress:'127.0.0.1',userAgent:'test',now:new Date('2026-07-20T00:00:00.000Z')}));}finally{database.close();remove(databasePath);}});

test('administrators inspect options and revoke another user sessions with history',()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`user-session-admin-${process.pid}.sqlite`);const config=loadConfig({databasePath});remove(databasePath);const database=openDatabase(config);try{migrateDatabase(database);seedDatabase(database,config,'Admin-User-Test-Password!');const auth=new AuthService(database,config);auth.login('funcionario1@demo.invalid','Admin-User-Test-Password!',{ipAddress:'127.0.0.1',userAgent:'session-a'});const service=new UserAdministrationService(database);const options=service.options(admin()) as {roles:unknown[];permissions:unknown[];companies:unknown[]};assert.ok(options.roles.length>=3);assert.ok(options.permissions.length>10);assert.ok(options.companies.length>=2);assert.equal((service.sessions(admin(),'user-employee-demo-0001') as {sessions:unknown[]}).sessions.length,1);assert.equal((service.revokeSessions(admin(),'user-employee-demo-0001') as {revoked:number}).revoked,1);assert.equal((service.sessions(admin(),'user-employee-demo-0001') as {sessions:unknown[]}).sessions.length,0);assert.throws(()=>service.revokeSessions(admin(),'user-demo-admin'),/SELF_SESSION_REVOCATION_FORBIDDEN/);assert.match(JSON.stringify(service.history(admin(),'user-employee-demo-0001')),/SESSIONS_REVOKED/);}finally{database.close();remove(databasePath);}});