import assert from 'node:assert/strict';
import { existsSync, rmSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { openDatabase } from '../database/db.js';
import { migrateDatabase } from '../database/migrate.js';
import { seedDatabase } from '../database/seed.js';
import { DocumentService, LocalDemoStorage, ProductionStorageAdapter } from '../server/documents.js';
import { loadConfig } from '../src/config.js';
import type { Principal } from '../server/types.js';
function remove(file:string):void{for(const candidate of [file,`${file}-wal`,`${file}-shm`])if(existsSync(candidate))rmSync(candidate,{recursive:true,force:true});}
function user(id:string,companyId:string,role:string):Principal{return{sessionId:`s-${id}`,userId:id,email:`${id}@demo.invalid`,displayName:id,companyId,roles:[role],permissions:['messages.write'],csrfToken:'csrf'};}
test('private documents validate content, checksum, company scope and soft deletion',()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`documents-${process.pid}.sqlite`);const storagePath=path.join(base.platformRoot,'data',`documents-storage-${process.pid}`);const config=loadConfig({databasePath,storagePath});remove(databasePath);remove(storagePath);const database=openDatabase(config);try{migrateDatabase(database);seedDatabase(database,config,'Existing-Demo-Password!');const service=new DocumentService(database,config,new LocalDemoStorage(storagePath));const owner=user('user-wholesale-demo-0001','company-demo-1','WHOLESALE');const created=service.upload(owner,{entityType:'COMPANY',entityId:owner.companyId,name:'comprovante.txt',mimeType:'text/plain',content:Buffer.from('DOCUMENTO DEMO')}) as {id:string;checksum:string};assert.equal(created.checksum.length,64);assert.equal(service.download(owner,created.id).content.toString(),'DOCUMENTO DEMO');assert.throws(()=>service.download(user('user-wholesale-demo-0002','company-demo-2','WHOLESALE'),created.id),/DOCUMENT_NOT_FOUND/);service.remove(owner,created.id);assert.throws(()=>service.download(owner,created.id),/DOCUMENT_NOT_FOUND/);assert.equal(Number(database.prepare("SELECT COUNT(*) AS total FROM audit_events WHERE entity_type='DOCUMENT'").get()?.total),2);}finally{database.close();remove(databasePath);remove(storagePath);}});
test('document storage rejects traversal, executables, oversized files and unprovisioned external storage',()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`documents-reject-${process.pid}.sqlite`);const storagePath=path.join(base.platformRoot,'data',`documents-reject-storage-${process.pid}`);const config=loadConfig({databasePath,storagePath});remove(databasePath);remove(storagePath);const database=openDatabase(config);try{migrateDatabase(database);seedDatabase(database,config,'Existing-Demo-Password!');const service=new DocumentService(database,config,new LocalDemoStorage(storagePath));const actor=user('user-demo-admin','company-demo-internal','ADMIN');assert.throws(()=>service.upload(actor,{entityType:'INTERNAL',name:'../evil.txt',mimeType:'text/plain',content:Buffer.from('x')}),/INVALID_DOCUMENT_TYPE/);assert.throws(()=>service.upload(actor,{entityType:'INTERNAL',name:'evil.exe',mimeType:'text/plain',content:Buffer.from('x')}),/INVALID_DOCUMENT_TYPE/);assert.throws(()=>service.upload(actor,{entityType:'INTERNAL',name:'large.txt',mimeType:'text/plain',content:Buffer.alloc(5*1024*1024+1)}),/INVALID_DOCUMENT_SIZE/);assert.throws(()=>new ProductionStorageAdapter().put('x',Buffer.from('x')),/NOT_PROVISIONED/);}finally{database.close();remove(databasePath);remove(storagePath);}});
