import assert from 'node:assert/strict';import { existsSync,rmSync } from 'node:fs';import path from 'node:path';import test from 'node:test';import { openDatabase } from '../database/db.js';import { migrateDatabase } from '../database/migrate.js';import { seedDatabase } from '../database/seed.js';import { AccountLifecycleService } from '../server/accounts.js';import { createPlatformApplication } from '../server/app.js';import { loadConfig } from '../src/config.js';
function remove(file:string):void{for(const candidate of [file,`${file}-wal`,`${file}-shm`])if(existsSync(candidate))rmSync(candidate,{recursive:true,force:true});}
test('extended platform APIs connect identity, documents, inbox, delivery, jobs, privacy and after-sales',async()=>{const base=loadConfig();const databasePath=path.join(base.platformRoot,'data',`extended-api-${process.pid}.sqlite`);const storagePath=path.join(base.platformRoot,'data',`extended-api-storage-${process.pid}`);const config=loadConfig({databasePath,storagePath});remove(databasePath);remove(storagePath);const database=openDatabase(config);migrateDatabase(database);seedDatabase(database,config,'Existing-Demo-Password!');const application=createPlatformApplication(database,config);await new Promise<void>(resolve=>application.server.listen(0,'127.0.0.1',resolve));try{const address=application.server.address();if(!address||typeof address==='string')throw new Error('SERVER_ADDRESS');const origin=`http://127.0.0.1:${address.port}`;const login=await fetch(`${origin}/api/auth/login`,{method:'POST',headers:{Origin:config.allowedOrigin,'Content-Type':'application/json'},body:JSON.stringify({email:'admin@demo.invalid',password:'Existing-Demo-Password!'})});assert.equal(login.status,200);const loginBody=await login.json() as {user:{csrfToken:string}};const cookie=login.headers.get('set-cookie')?.split(';')[0]??'';const headers={Origin:config.allowedOrigin,'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':loginBody.user.csrfToken};const write=(route:string,body:unknown,method='POST')=>fetch(`${origin}${route}`,{method,headers,body:JSON.stringify(body)});
 const invite=await write('/api/admin/invitations',{email:'api.invite@demo.invalid',displayName:'API Invite',roleId:'role-employee',companyId:'company-demo-internal'});assert.equal(invite.status,201);assert.equal(Number(database.prepare("SELECT COUNT(*) count FROM delivery_outbox WHERE template_code='INVITE'").get()?.count),1);
 const sessions=await fetch(`${origin}/api/account/sessions`,{headers:{Cookie:cookie}});assert.equal(sessions.status,200);
 const mfa=await write('/api/account/mfa/start',{});assert.equal(mfa.status,201);const code=new AccountLifecycleService(database,config).currentTotpForDemo('user-demo-admin');assert.equal((await write('/api/account/mfa/confirm',{code})).status,200);
 const team=await write('/api/teams',{name:'Equipe HTTP DEMO',companyId:'company-demo-internal'});assert.equal(team.status,201);const teamBody=await team.json() as {id:string};assert.equal((await write(`/api/teams/${teamBody.id}/members`,{userId:'user-employee-demo-0001',memberRole:'LEAD'})).status,201);
 const document=await write('/api/documents',{companyId:'company-demo-internal',entityType:'INTERNAL',name:'api-demo.txt',mimeType:'text/plain',contentBase64:Buffer.from('ARQUIVO HTTP DEMO').toString('base64')});assert.equal(document.status,201);const documentBody=await document.json() as {id:string};const download=await fetch(`${origin}/api/documents/${documentBody.id}`,{headers:{Cookie:cookie}});assert.equal(await download.text(),'ARQUIVO HTTP DEMO');
 const inbox=await fetch(`${origin}/api/inbox?priority=NORMAL`,{headers:{Cookie:cookie}});assert.equal(inbox.status,200);const inboxBody=await inbox.json() as {cases:{id:string}[]};assert.ok(inboxBody.cases.length>0);assert.equal((await write(`/api/inbox/${inboxBody.cases[0]?.id}`,{status:'WAITING_INTERNAL',priority:'HIGH',tags:['HTTP']},'PATCH')).status,200);
 const delivery=await write('/api/deliveries',{channel:'EMAIL',templateCode:'NEW_MESSAGE',recipient:'preview@demo.invalid',variables:{message:'Teste HTTP'},companyId:'company-demo-internal'});assert.equal(delivery.status,201);assert.equal((await write('/api/admin/deliveries/process',{})).status,200);const deliveryList=await fetch(`${origin}/api/deliveries`,{headers:{Cookie:cookie}});assert.match(await deliveryList.text(),/NÃO ENVIADA EXTERNAMENTE/);
 assert.equal((await write('/api/privacy/requests',{type:'EXPORT',notes:'Solicitação HTTP DEMO'})).status,201);assert.equal((await fetch(`${origin}/api/privacy/export`,{headers:{Cookie:cookie}})).status,200);assert.equal((await fetch(`${origin}/api/admin/jobs`,{headers:{Cookie:cookie}})).status,200);
 const order=database.prepare('SELECT id FROM orders LIMIT 1').get();assert.ok(order);database.prepare("UPDATE orders SET status='DELIVERED' WHERE id=?").run(String(order.id));const orderItem=database.prepare('SELECT id FROM order_items WHERE order_id=? LIMIT 1').get(String(order.id));assert.ok(orderItem);const createdReturn=await write('/api/returns',{orderId:String(order.id),reasonCode:'HTTP_DEMO',notes:'Devolução criada via API',items:[{orderItemId:String(orderItem.id),quantity:1}]});assert.equal(createdReturn.status,201);assert.equal((await fetch(`${origin}/api/orders/${order.id}/timeline`,{headers:{Cookie:cookie}})).status,200);
 const reset=await fetch(`${origin}/api/auth/password-reset/request`,{method:'POST',headers:{Origin:config.allowedOrigin,'Content-Type':'application/json'},body:JSON.stringify({email:'missing@demo.invalid'})});assert.equal(reset.status,202);assert.equal(Number(database.prepare("SELECT COUNT(*) count FROM delivery_outbox WHERE template_code='PASSWORD_RESET'").get()?.count),0);const validReset=await fetch(`${origin}/api/auth/password-reset/request`,{method:'POST',headers:{Origin:config.allowedOrigin,'Content-Type':'application/json'},body:JSON.stringify({email:'funcionario1@demo.invalid'})});assert.equal(validReset.status,202);assert.equal(Number(database.prepare("SELECT COUNT(*) count FROM delivery_outbox WHERE template_code='PASSWORD_RESET'").get()?.count),1);
}finally{await new Promise<void>(resolve=>application.server.close(()=>resolve()));database.close();remove(databasePath);remove(storagePath);}});
